### ISSUE TITLE
Problem "Not authorized" building with Maven

### ISSUE THREAD

**Issue by dazed19** [atricore/josso2#5]
Hi

I've hit a problem trying to build via Maven.

> `[ERROR] Failed to execute goal on project org.atricore.josso.branding: Could not resolve dependencies for project org.atricore.josso:org.atricore.josso.branding:bundle:2.4.2: Could not transfer artifact org.atricore.idbus.kernel.common:org.atricore.idbus.kernel.common.boot:jar:1.4.2 from/to atricore-m2-commercial-repo (http://repository.atricore.com/m2-release-repository): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]`

Is it possible there is some build depencancy from open source version to commercial version?

**Comment by sgonzalezoyuela** [comment]
updated after migrated repo
