### ISSUE TITLE
Download links are broken :)

### ISSUE THREAD

**Issue by timcharper** [atricore/josso2#7]
https://iam.tf/downloads/

Points to:

https://github.com/atricore/josso2/releases/download/3.0.8/iam.tf-1.0.9-unix.jar

I think the correct link is:

https://github.com/atricore/josso2/releases/download/3.0.9/iam.tf-1.0.9-unix.jar

Cheers!

**Comment by sgonzalezoyuela** [comment]
Hi Tim,

Hey there! Thanks for pointing that out. We really appreciate your help in keeping our information accurate. The link you provided is the correct one, so we've updated it. Sorry for any confusion this may have caused. Cheers!
